// <auto-generated />
using ASPdotNET_ReactdotJS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPdotNET_ReactdotJS.Migrations
{
    [DbContext(typeof(WebSiteContext))]
    [Migration("20230504013029_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ASPdotNET_ReactdotJS.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemsModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 1,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 2,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "Highlander"
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 3,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "Highlander II"
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 4,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "The Last of the Mohicans"
                        },
                        new
                        {
                            Id = 5,
                            ImageId = 5,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "Police Academy 6"
                        },
                        new
                        {
                            Id = 6,
                            ImageId = 6,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "Rear Window"
                        },
                        new
                        {
                            Id = 7,
                            ImageId = 7,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "Road House"
                        },
                        new
                        {
                            Id = 8,
                            ImageId = 8,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 9,
                            ImageId = 9,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "Star Treck IV"
                        },
                        new
                        {
                            Id = 10,
                            ImageId = 10,
                            ItemType = 1,
                            Ranking = 0,
                            Title = "Superman 4"
                        },
                        new
                        {
                            Id = 11,
                            ImageId = 11,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Abbey Road"
                        },
                        new
                        {
                            Id = 12,
                            ImageId = 12,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Adrenalize"
                        },
                        new
                        {
                            Id = 13,
                            ImageId = 13,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Back in Black"
                        },
                        new
                        {
                            Id = 14,
                            ImageId = 14,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Enjoy the Silence"
                        },
                        new
                        {
                            Id = 15,
                            ImageId = 15,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Parachutes"
                        },
                        new
                        {
                            Id = 16,
                            ImageId = 16,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Ride the Lightning"
                        },
                        new
                        {
                            Id = 17,
                            ImageId = 17,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Rock or Bust"
                        },
                        new
                        {
                            Id = 18,
                            ImageId = 18,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "Rust in Peace"
                        },
                        new
                        {
                            Id = 19,
                            ImageId = 19,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "St. Anger"
                        },
                        new
                        {
                            Id = 20,
                            ImageId = 20,
                            ItemType = 2,
                            Ranking = 0,
                            Title = "The Final Countdown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
